{% set name = "ktch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ktch-{{ version }}.tar.gz
  sha256: 5a22961d26b46c5f9e9b06b4036d9ad2e931171faee9114ca899d8407a2b5190

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<3.12
    - numpy >=1.22.0,<2.0.0
    - pandas >=1.4.0,<2.0.0
    - scikit-learn >=1.2.0,<2.0.0
    - scipy >=1.8.0,<2.0.0
    - toml >=0.10.0,<0.11.0

test:
  imports:
    - ktch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://doc.ktch.dev
  summary: ktch is a python package for model-based morphometrics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noshita
