{% set name = "ktch" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ktch-{{ version }}.tar.gz
  sha256: 4b8479e7d5963508b29e8df98a4a0ed2c08ab8d9501f03eeed6ba5f13c097940

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy >=1.22.0,<2.0.0
    - pandas[pyarrow] >=1.5.0,<3.0.0
    - scikit-learn >=1.2.0,<2.0.0
    - scipy >=1.8.0,<2.0.0
    - toml >=0.10.0,<0.11.0

test:
  imports:
    - ktch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://doc.ktch.dev
  summary: ktch is a python package for model-based morphometrics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noshita
