{% set name = "ktch" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ktch-{{ version }}.tar.gz
  sha256: d60b7d7118f670d4957e2f6bacf5f73792f95853e788c3397d87ad1cf8ae4fa5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<3.12
    - numpy >=1.22.0,<2.0.0
    - pandas[pyarrow] >=1.5.0,<3.0.0
    - scikit-learn >=1.2.0,<2.0.0
    - scipy >=1.8.0,<2.0.0
    - toml >=0.10.0,<0.11.0

test:
  imports:
    - ktch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://doc.ktch.dev
  summary: ktch is a python package for model-based morphometrics.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noshita
