{% set name = "ktch" %}
{% set version = "0.4.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ktch-{{ version }}.tar.gz
  sha256: d60b7d7118f670d4957e2f6bacf5f73792f95853e788c3397d87ad1cf8ae4fa5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - pandas >=2.2
    - scikit-learn >=1.6
    - scipy >=1.13

test:
  imports:
    - ktch
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://doc.ktch.dev/
  summary: ktch is a python package for model-based morphometrics.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/noshita/ktch
  doc_url: https://doc.ktch.dev/

extra:
  recipe-maintainers:
    - noshita
