{% set name = "ktch" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ktch-{{ version }}.tar.gz
  sha256: 01e5a36919e65fb14e4872bcf280a9b05b5a829d16e0085159f77b9f1ad2ac28

build:
  noarch: python
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=1.26
        - pandas >=2.2
        - scikit-learn >=1.6
        - scipy >=1.13
    test:
      imports:
        - ktch
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-plot
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - matplotlib-base >=3.10.7
        - plotly <6.0
        - seaborn >=0.13.2
    test:
      imports:
        - ktch.plot
        - matplotlib

  - name: {{ name }}-all
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name + '-plot', exact=True) }}
    test:
      imports:
        - {{ name }}
        - matplotlib
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://doc.ktch.dev/
  summary: ktch is a python package for model-based morphometrics.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/noshita/ktch
  doc_url: https://doc.ktch.dev/

extra:
  recipe-maintainers:
    - noshita
